### ISSUE TITLE
Update pystac-client return methods.

### ISSUE THREAD

**Issue by sharkinsspatial** [developmentseed/asdi-examples#7]
`get_all_items` is now deprecated and should be replaced https://pystac-client.readthedocs.io/en/stable/api.html#pystac_client.ItemSearch.items.
https://app.reviewnb.com/developmentseed/asdi-examples/blob/main/examples%2Fcop-dem-glo-30-stac-access.ipynb

**Comment by wildintellect** [comment]
adding reference from @sharkinsspatial to look at https://github.com/aws/studio-lab-examples for managing conda envs

**Comment by wildintellect** [comment]
I'm actually a tad lost on this conversation https://github.com/stac-utils/pystac-client/issues/237
It seems `get_all_items` was deprecated but then `item_collection` was added back, and functionally is a drop in replacement. https://github.com/stac-utils/pystac-client/blob/69c3bdf6f79cfca697d32518873e0f57c217cddd/pystac_client/item_search.py#L745
But the intent of this ticket I think was to switch to `items` which is an iterator then that's a little different.
Based on the ticket above, I think best practices would imply adding a `max_items` to the request, but I'm open to being convinced to use the iterator.

**Comment by wildintellect** [comment]
Went with `item_collection` and `max_items` for now.
